### ISSUE TITLE
Failure to build with go1.23 and above

### ISSUE THREAD

**Issue by sudhackar** [rogpeppe/go-internal#289]
```console
$ go version && go build
go version go1.24.0 linux/amd64
# github.com/rogpeppe/go-internal/testscript
./exe_go118.go:14:27: cannot use nopTestDeps{} (value of struct type nopTestDeps) as testing.testDeps value in argument to testing.MainStart: nopTestDeps does not implement testing.testDeps (missing method InitRuntimeCoverage)
(staging Source Store)
```

From https://pkg.go.dev/testing/internal/testdeps

It  was added in go1.23.0

Just adding this passes the build
```diff
diff --git a/testscript/exe_go123.go b/testscript/exe_go123.go
new file mode 100644
index 0000000..72ececf
--- /dev/null
+++ b/testscript/exe_go123.go
@@ -0,0 +1,8 @@
+//go:build go1.23
+// +build go1.23
+
+package testscript
+
+func (n nopTestDeps) InitRuntimeCoverage() (mode string, tearDown func(coverprofile string, gocoverdir string) (string, error), snapcov func() float64) {
+	return "", nil, nil
+}
```

**Comment by mvdan** [comment]
You're on a very old version of testscript. The latest version and master are continuously tested on both Go 1.23 and 1.24.
